#
# Example Settings
#
# This file can contain settings for your Flow application that override
# the various defaults defined by other packages.
#
# Copy this file to Settings.yaml, and adjust as necessary.
#
# For possible configuration options you may refer to the packages'
# default settings file(s) in the corresponding package directories (for
# example, Packages/Framework/Neos.Flow/Configuration/Settings.yaml)
# or read the fine manuals.

Neos:
  Flow:
    persistence:
      backendOptions:
        driver: pdo_mysql
        charset: utf8mb4
        host: 127.0.0.1
        dbname: bitnami_neos
        user: bn_neos
        password: 9d5c846038
    mvc:
      routes:
        Neos.Flow: true
    core:
      phpBinaryPathAndFilename: 'C:\Bitnami\neos-4.1.7-0/php/php.exe'
    resource:
      publishing:
        fileSystem:
          mirrorMode: copy
  Imagine:
    driver: Gd
    